name: Deploy to Ubuntu Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            set -e
            cd /var/www/liquid-vanilla
          
            # Update repository
            git fetch origin master
            git reset --hard origin/master
          
            # Backend setup
            cd backend
            python3.12 -m venv .venv
            source .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
          
            # Frontend setup
            cd ../frontend
            rm -rf node_modules package-lock.json
            npm install
            npm run build
          
            # Restart services
            sudo /usr/sbin/service nginx restart
            sudo /usr/bin/supervisorctl restart liquid-vanilla
          EOF